<?php

/**
 * @file
 * Main file for hooks and custom functions.
 */

/**
 * Implements hook_form_alter().
 */
function druio_form_search_block_form_alter(&$form, $form_state, $form_id) {
  $button = '<i class="fa fa-search" aria-hidden="true"></i>';
  $form['actions']['submit']['#prefix'] = $button;
  $form['actions']['submit']['#value'] = '';
  $form['keys']['#placeholder'] = 'Поиск по сообществу';
}

/**
 * DON'T FORGET TO REMOVE IT.
 *
 * Used for testing purposes.
 */
function druio_preprocess_node(&$variables) {
  $node = $variables['node'];
  ksm($node->field_project_development_status);
}
