<?php

/**
 * @file
 * Main file for hooks and custom functions.
 */

/**
 * Implements hook_form_alter().
 */
function druio_form_search_block_form_alter(&$form, $form_state, $form_id) {
  $button = '<i class="fa fa-search" aria-hidden="true"></i>';
  $form['actions']['submit']['#prefix'] = $button;
  $form['actions']['submit']['#value'] = '';
  $form['keys']['#placeholder'] = 'Поиск по сообществу';
}
