<?php

/**
 * @file
 * Module for projects.
 */

/**
 * Implements hook_menu().
 */
function druio_projects_menu() {
  $items = array();

  $items['druio/project/ajax-add'] = array(
    'page callback' => 'druio_projects_ajax_add',
    'access callback' => TRUE,
  );

  $items['druio/project/update'] = array(
    'page callback' => 'druio_projects_update',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_ds_fields_info().
 */
function druio_projects_ds_fields_info($entity_type) {
  // Entity: Node.
  if ($entity_type == 'node') {
    $fields['projects_downloads'] = array(
      'title' => 'Project: Downloads',
      'ui_limit' => array('project|*'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'druio_projects_downloads',
    );

    $fields['projects_drupalorg_link'] = array(
      'title' => 'Project: Drupal.org link',
      'ui_limit' => array('project|*'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'druio_projects_drupalorg_link',
    );

    $fields['projects_questions'] = array(
      'title' => 'Project: Questions',
      'ui_limit' => array('project|*'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'druio_projects_questions',
    );

    return array($entity_type => $fields);
  }
  return;
}

/**
 * Project downloads field.
 *
 * @param array $field
 *
 * @return string
 */
function druio_projects_downloads($field) {
  $entity = $field['entity'];

  $release_values = field_get_items('node', $entity, 'field_project_releases');
  $releases = (array) json_decode($release_values[0]['value']);
  krsort($releases);

  $download_form = drupal_get_form('druio_projects_download_form', $releases, $entity);

  return drupal_render($download_form);
}

/**
 * Link to original project page.
 *
 * @param array $field
 *
 * @return string
 */
function druio_projects_drupalorg_link($field) {
  $field_project_short_name = field_get_items('node', $field['entity'], 'field_project_short_name');
  $project_machine_name = $field_project_short_name[0]['safe_value'];

  $html = '<a href="@url_to_project" target="_blank">@label</a>';
  $data = array(
    '@url_to_project' => 'https://drupal.org/project/' . $project_machine_name,
    '@label' => $field['entity']->title . ' на Drupal.org',
  );

  return format_string($html, $data);
}

/**
 * Question referenced to this project.
 *
 * @param array $field
 *
 * @return string
 */
function druio_projects_questions($field) {
  $html = '<h2 class="title">Вопросы по проекту</h2>';
  $html .= views_embed_view('question_nodes', 'questions_in_project');

  return $html;
}

/**
 * Download form for project.
 *
 * @param array $releases
 * @param object $entity
 *
 * @return mixed
 */
function druio_projects_download_form($form, &$form_state, $releases, $entity) {
  $release_selector_options = array();
  $release_selector_data = array();
  $release_info_markup = '';

  foreach ($releases as $major_version => $minor_releases) {
    foreach ((array) $minor_releases as $minor_version => $release_info) {
      $release_selector_options[$major_version][$minor_version] = $minor_version;
      $release_selector_data[$major_version][$minor_version] = $release_info;
    }
  }

  // If user select version, we show release information.
  if (!empty($form_state['values']['release_selector'])) {
    $major_version_pattern = "/^(.\\.x)/";
    preg_match($major_version_pattern, $form_state['values']['release_selector'], $matches);
    if (!empty($matches[0])) {
      $major_version_selected = $matches[0];
      $release_info_markup = theme('druio_projects_downloads_release', array(
          'release_info' => (array) $release_selector_data[$major_version_selected][$form_state['values']['release_selector']],
          'entity' => $entity,
        )
      );
    }
  }
  // Default version download.
  else {
    $priority = array(
      '7.x',
      '6.x',
      '8.x',
    );

    foreach ($priority as $version) {
      if (!empty($release_selector_data[$version])) {
        $version_info = $release_selector_data[$version];
        $latest_release_version = key($version_info);

        $release_info_markup = theme('druio_projects_downloads_release', array(
            'release_info' => (array) $release_selector_data[$version][$latest_release_version],
            'entity' => $entity,
          )
        );
        break;
      }
    }
  }

  $form['release_selector'] = array(
    '#type' => 'select',
    '#title' => 'Выбор версии для загрузки',
    '#options' => $release_selector_options,
    '#default_value' => isset($latest_release_version) ? $latest_release_version : NULL,
    '#ajax' => array(
      'callback' => 'druio_projects_download_form_ajax_info',
      'wrapper' => 'druio-projects-download-info',
    ),
  );

  $form['release_info'] = array(
    '#markup' => $release_info_markup,
    '#prefix' => '<div id="druio-projects-download-info">',
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * Ajax release info update.
 *
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function druio_projects_download_form_ajax_info($form, $form_state) {
  return $form['release_info'];
}

/**
 * Implements hook_theme().
 */
function druio_projects_theme() {
  // Tracker icon in header.
  $theme['druio_projects_downloads_release'] = array(
    'template' => 'theme/druio-projects-downloads-release',
    'variables' => array(
      'release_info' => NULL,
      'entity' => NULL,
    ),
  );

  return $theme;
}

/**
 * Add project via ajax.
 */
function druio_projects_ajax_add() {
  $result = FALSE;

  if (!empty($_POST['project'])) {
    $post = strtolower($_POST['project']);
    $project = new DruioProjects();

    if (filter_var($post, FILTER_VALIDATE_URL)) {
      $project_name = $project->parseProjectNameFromUrl($post);
    }
    else {
      $project_name = $post;
    }

    // Add project, if exist, update info.
    $add_result = $project->addProject($project_name, TRUE);

    switch ($add_result) {
      case 1:
        $result = 'Проект успешно добавлен в базу.';
        break;

      case 2:
        $result = 'Drupal.org не отвечает, или вы указали несуществующий проект.';
        break;

      case 3:
      case 4:
        $result = 'Проект уже имеется в нашей базе. Информация о модуле успешно обновлена.';
        break;
    }
  }

  drupal_json_output($result);
  drupal_exit();
}

/**
 * Update project.
 */
function druio_projects_update() {
  $result = FALSE;

  if (!empty($_POST['project'])) {
    $post = strtolower($_POST['project']);
    $project = new DruioProjects();

    if (filter_var($post, FILTER_VALIDATE_URL)) {
      $project_name = $project->parseProjectNameFromUrl($post);
    }
    else {
      $project_name = $post;
    }

    $add_result = $project->updateProject($project_name);

    switch ($add_result) {
      case 1:
        $result = 'Проект успешно добавлен в базу.';
        break;

      case 2:
        $result = 'Drupal.org не отвечает.';
        break;

      case 3:
        $result = 'Проект обновлен.';
        break;
    }
  }

  drupal_json_output($result);
  drupal_exit();
}

/**
 * Implements hook_filter_info().
 */
function druio_projects_filter_info() {
  $filters['druio_projects_auto_projects'] = array(
    'title' => 'Dru.io Projects - auto add and update.',
    'description' => 'This filter detect links to Drupal projects and add them to our base, if project already exists project will be update.',
    'process callback' => '_druio_projects_auto_projects',
  );

  return $filters;
}

/**
 * Process filter.
 *
 * @param string $text
 * @param $filter
 *
 * @return string
 */
function _druio_projects_auto_projects($text, $filter) {
  $druio_projects = new DruioProjects();
  $projects = $druio_projects->parseProjectsFromHtmlLinks($text);

  if (!empty($projects)) {
    foreach ($projects as $project_name) {
      $druio_projects->addProject($project_name);
    }
  }

  return $text;
}

/**
 * Implements hook_form_FORM_ID_alter() for question_node_form().
 *
 * Alter question node form and add button for project submission.
 */
function druio_projects_form_question_node_form_alter(&$form, &$form_state, $form_id) {
  // Just make sure field is exist.
  if (isset($form['field_project_reference'])) {
    // Attach our js.
    $path = drupal_get_path('module', 'druio_projects');
    drupal_add_js($path . '/js/druio_projects.js');
    // Add link to description.
    $form['field_project_reference'][LANGUAGE_NONE]['#description'] .= format_string(
      '<br /><@tag>@description !link</@tag>',
      array(
        '@tag' => 'div',
        '@description' => 'Если нужный проект отстуствует, вы можете добавить его самостоятельно.',
        '!link' => '<a href="#" id="add-project-button">Добавить проект в базу.</a>',
      )
    );
  }
}
