FROM php:7.2-fpm-alpine

RUN apk add --no-cache git openssl \
    && apk add --no-cache --virtual .persistent-deps postgresql-dev icu-dev libmcrypt-dev \
    && apk add --no-cache --virtual .build-deps build-base gmp-dev zlib-dev \
    && docker-php-ext-install mbstring opcache pdo pdo_pgsql zip \
    # gmp - causes Unable to load dynamic library 'gmp.so' \
    # Cleanup
    && apk del .build-deps \
    && rm -rf /tmp/*

# Install PHP Extensions
RUN apk add --no-cache --virtual .build-deps build-base autoconf git \
    && yes | pecl install apcu xdebug ast igbinary redis \
    # intl - causes error: Unable to detect ICU prefix
    && echo "extension=igbinary.so" > /usr/local/etc/php/conf.d/igbinary.ini \
    && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini \
    # APCU config
    && echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apcu.ini \
    && echo "apc.enable_cli=1" >> /usr/local/etc/php/conf.d/apcu.ini \
    # AST config
    && echo "extension=ast.so" > /usr/local/etc/php/conf.d/ast.ini \
    # Xdebug config
    && echo "zend_extension=xdebug.so" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable = 1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart = 1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host = 10.254.254.254" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.max_nesting_level = 1000" >> /usr/local/etc/php/conf.d/xdebug.ini \
    # Cleanup
    && apk del .build-deps \
    && rm -rf /tmp/*

# Add Composer
ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl --silent --show-error https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer && \
    composer global require hirak/prestissimo && \
    composer clear-cache

WORKDIR /var/www/html
VOLUME /var/www/html

COPY docker/php/www.conf /usr/local/etc/php-fpm.d/www.conf
ENV APP_ENV dev
CMD ["php-fpm", "--allow-to-run-as-root"]

#ADD composer.json composer.lock ./
#RUN composer install --no-scripts --no-autoloader --no-suggest \
#    && composer clear-cache
#
#COPY . /var/www/html
#
#RUN composer dump --optimize
#RUN bin/console -e=prod cache:warmup
