<?php

/**
 * @file
 * Install and uninstall logic for the Honeypot Entityform module.
 */

/**
 * Implements hook_uninstall().
 */
function honeypot_entityform_uninstall() {
  if (!$entityform_types = entity_load_multiple_by_name('entityform_type', FALSE)) {
    return;
  }

  // Delete all remaining honeypot entity form type variables.
  foreach ($entityform_types as $key => $entityform_type) {
    variable_delete("honeypot_form_{$key}_entityform_edit_form");
  }
}
