<?php

/**
 * @file
 * Main module file for the Honeypot Entityform module.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function honeypot_entityform_form_honeypot_admin_form_alter(&$form, &$form_state) {
  if (!$entityform_types = entity_load_multiple_by_name('entityform_type', FALSE)) {
    return;
  }

  $form['enabled_forms']['entityform_types'] = array(
    '#type' => 'item',
    '#title' => t('Entity Forms'),
  );

  // Add a checkbox for each entity form type.
  foreach ($entityform_types as $key => $entityform_type) {
    $form['enabled_forms']['entityform_types']["honeypot_form_{$key}_entityform_edit_form"] = array(
      '#type' => 'checkbox',
      '#title' => entity_label('entityform_type', $entityform_type),
      '#default_value' => variable_get("honeypot_form_{$key}_entityform_edit_form", FALSE),
    );
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function honeypot_entityform_entityform_type_delete($entity) {
  // Clean up the corresponding honeypot variable.
  $key = entity_id('entityform_type', $entity);
  variable_delete("honeypot_form_{$key}_entityform_edit_form");
}
