<?php
/**
 * Ace BUEditor
 * by Alan Bondarchuk <imacoda@gmail.com>
 *
 * Provides a toolbar button for writing code with Ace in BUEditor.
 * For the next generation of Russian Drupal Community
 * http://community.drupalife.com
 *
*/

/**
 * Implements hook_preprocess_html().
 */
function acebueditor_preprocess_html(&$vars) {
  $module_path = drupal_get_path('module', 'acebueditor');
  drupal_add_js($module_path . '/js/ace.bueditor.js', array('weight' => 100));
  drupal_add_css($module_path . '/css/ace.bueditor.css', array('weight' => 100));
}
