<?php

/*
 * Implementation of hook_views_api()
 */
function views_exported_views_api() {
  return array('api' => 3.0);
}

/**
 * Implements hook_views_default_views().
 **/
function views_exported_views_default_views() {
  //Finds all files that match a given mask in a given directory
  //In our case, looks for any files named *.inc in the /views directory
  $files = file_scan_directory(drupal_get_path('module', 'views_exported'). '/views', '/.inc/');
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  //Check that there are views in the directory
  //This keeps the site from throwing errors if there are no views to return
  if ($views) {
    return $views;
  }
}
