<?php

/**
 * @file
 * Contains druio_question.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function druio_question_entity_extra_field_info() {
  $extra = [];

  $extra['node']['question']['display']['druio_question_meta'] = [
    'label' => 'Dru.io Question: Meta info',
    'description' => 'Drupal version, tags and categories.',
    'weight' => '100',
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function druio_question_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('druio_question_meta')) {
    $build['druio_question_meta'] = [
      '#theme' => 'druio_question_meta_field',
      '#entity' => $entity,
    ];
  }
}

/**
 * Implements hook_theme().
 */
function druio_question_theme($existing, $type, $theme, $path) {
  $file = 'druio_question.theme.inc';
  return [
    'druio_question_meta_field' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => $file,
    ],
  ];
}