<?php

/**
 * @file
 * Contains druio_question.module.
 */

use Drupal\comment\CommentInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function druio_question_entity_extra_field_info() {
  $extra = [];

  $extra['node']['question']['display']['druio_question_meta'] = [
    'label' => 'Dru.io Question: Meta info',
    'description' => 'Drupal version, tags and categories.',
    'weight' => '100',
    'visible' => FALSE,
  ];

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function druio_question_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('druio_question_meta')) {
    $build['druio_question_meta'] = [
      '#theme' => 'druio_question_meta_field',
      '#entity' => $entity,
    ];
  }
}

/**
 * Implements hook_theme().
 */
function druio_question_theme($existing, $type, $theme, $path) {
  $file = 'druio_question.theme.inc';
  return [
    'druio_question_meta_field' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => $file,
    ],
  ];
}

/**
 * Implements hook_node_links_alter().
 */
function druio_question_node_links_alter(array &$links, NodeInterface $entity, array &$context) {
  $current_user = \Drupal::currentUser();
  if ($entity->bundle() == 'question' && $context['view_mode'] == 'full') {
    // Remove default links. They are works incorrect with two comment fields.
    unset($links['comment__field_question_answers']);
    unset($links['comment__field_comments']);

    if ($current_user->isAuthenticated()) {
      $links['druio_question'] = [
        '#theme' => 'links',
        '#links' => [
          'answer-add' => [
            'title' => 'Добавить ответ',
            'url' => Url::fromRoute('comment.reply', [
              'entity_type' => $entity->getEntityTypeId(),
              'entity' => $entity->id(),
              'field_name' => 'field_question_answers',
            ]),
          ],
          'comment-add' => [
            'title' => 'Добавить комментарий',
            'url' => Url::fromRoute('comment.reply', [
              'entity_type' => $entity->getEntityTypeId(),
              'entity' => $entity->id(),
              'field_name' => 'field_comments',
            ]),
          ],
        ],
      ];
    }
  }
}


/**
 * Implements hook_comment_links_alter().
 */
function druio_question_comment_links_alter(array &$links, CommentInterface $entity, array &$context) {
  if ($entity->bundle() == 'question_answer' && $context['view_mode'] == 'default') {
    $links['comment']['#links']['comment-reply']['title'] = 'Добавить комментарий';
    $links['comment']['#links']['comment-reply']['url'] = Url::fromRoute('comment.reply', [
      'entity_type' => $entity->getEntityTypeId(),
      'entity' => $entity->id(),
      'field_name' => 'field_question_answer_comments',
    ]);
  }
}