<?php
/**
 * @file
 * menu_link.f3aa4e71405f1a252d229e24df23187f5c0eef24.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/config',
  'link_title' => 'Level three',
  'menu_name' => 'menu-test',
  'weight' => '-50',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'admin/config',
  'parent_identifier' => '3bd4fee5d9b3477e3f30a17def41c14b99bdd3b8',
);

$dependencies = array(
  'menu_link.3bd4fee5d9b3477e3f30a17def41c14b99bdd3b8' => 'menu_link.3bd4fee5d9b3477e3f30a17def41c14b99bdd3b8',
);

$optional = array();

$modules = array();
