<?php
/**
 * @file
 * menu_link.a6d0f08452ba53fd1b8cf291ed73479f86c70552.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin',
  'link_title' => 'Level one',
  'menu_name' => 'menu-test',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'admin',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.menu_test' => 'menu.menu_test',
);

$optional = array();

$modules = array();
