<?php
/**
 * @file
 * menu_link.3bd4fee5d9b3477e3f30a17def41c14b99bdd3b8.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'admin/content',
  'link_title' => 'Level two',
  'menu_name' => 'menu-test',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
  ),
  'router_path' => 'admin/content',
  'parent_identifier' => 'a6d0f08452ba53fd1b8cf291ed73479f86c70552',
);

$dependencies = array(
  'menu_link.a6d0f08452ba53fd1b8cf291ed73479f86c70552' => 'menu_link.a6d0f08452ba53fd1b8cf291ed73479f86c70552',
);

$optional = array();

$modules = array();
