<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.article' => 'ff81b2503f97b8ec6e6ba2eeef572f5e8e64365f',
  'field.node.body.article' => '78f3cfa393218e9d74a91caf681c6067d9a8ce6a',
  'vocabulary.tags' => '36a9325f71dc343299f61677a58260d6ce8a8026',
);

// The following modules are required to run the configurations of this file.

$modules = array (
  0 => 'node',
  1 => 'field_sql_storage',
  2 => 'text',
  4 => 'taxonomy',
  6 => 'image',
);
